#ifndef CONSTANTS_HPP_
#define CONSTANTS_HPP_

#define FRAME_WIDTH  640
#define FRAME_HEIGHT 480

#define HEAD_MINIMUM_SATURATION 25.0

#define HEAD_MINIMUM_BRIGHTNESS 30.0
#define HEAD_MAXIMUM_BRIGHTNESS 220.0

#endif /* CONSTANTS_HPP_ */
